In [31]:
import pandas as pd
import numpy as np

## 数据的导入与导出

In [ ]:
# 数据的导入
df = pd.read_csv('data/employees.csv')

print(type(df))
print(df.tail())
df.salary.mean()

df = df.tail()
# 数据导出
df.to_csv('data/new.csv')

<class 'pandas.DataFrame'>
     employee_id first_name last_name     email  phone_number      job_id  \
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
102   6000.0             NaN       201.0           20.0
103   6500.0             NaN       101.0           40.0
104  10000.0             NaN       101.0           70.0
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0

In [29]:
# json
df = pd.read_json('data/data1.json')
df

import json

with open('data/test.json', 'r') as f:
    data = json.load(f)

df = pd.DataFrame(data['users'])
df

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

## 缺失值处理

In [ ]:
s = pd.Series([1, 2, np.nan, None, pd.NA])
df = pd.DataFrame([[1, pd.NA, 2], [2, 3, 5], [np.nan, 4, 6]], columns=['第一列', '第二列', '第三列'])

print(s.isna())
print(s.isna().sum())

print(df.isna())
print(df.isna().sum())

0    False
1    False
2     True
3     True
4     True
dtype: bool
3
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
第一列    1
第二列    1
第三列    0
dtype: int64

In [ ]:
# 删除缺失值
print(s.dropna())

print(df.dropna()) # 删除带缺失值的一整条记录
print(df.dropna(how='all')) # 当这一条记录中都是缺失值才删除
print(df.dropna(thresh=2)) # 如果至少有n个值不是缺失值，就保留
print(df.dropna(axis=1)) # 删除一列的记录
print(df.dropna(subset=['第一列'])) # 指定查找某一列如果有缺失值，就删除一整行

0    1
1    2
dtype: object
   第一列 第二列  第三列
1  2.0   3    5
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第三列
0    2
1    5
2    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5

In [64]:
# 填充缺失值

df = pd.read_csv('data/weather_withna.csv')

# df.tail()
print(df.isna().sum())

# 使用字典填充
print(df.fillna({'temp_max': 20, 'wind': 2.5}).tail())

# 用平均值填充
print(df.fillna(df[['wind']].mean()).tail())

# 用前面相邻的值填充
print(df.ffill().tail())

# 用后面相邻的值填充
print(df.bfill().tail())

date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind weather
1456  2015-12-27            NaN       NaN       NaN  3.242055     NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055     NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055     NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055     NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

## 重复数据处理

In [66]:
data = {
    'name': ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    'age': [26, 25, 30, 25, 35, 30],
    'city': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [70]:
# 重复数据检测
df.duplicated()
df.drop_duplicates(subset=['name']) # 根据指定列去重
df.drop_duplicates(subset=['name'], keep='last') # 保留最新的数据，重复的删除前边的

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

## 数据类型的转换

In [ ]:
df = pd.read_csv('data/sleep.csv')
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [74]:
df['age'] = df['age'].astype('int16')
df.dtypes

person_id                    int64
gender                         str
age                          int16
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [77]:
df['gender'] = df['gender'].astype('category')
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']

## 清洗格式错误数据

In [88]:
# 格式化日期
data = {
    'Date': ['2020/12/01', '2020/12/02' , '20201226'],
    'duration': [50, 40, 45]
}

df = pd.DataFrame(data, index=['day1', 'day2', 'day3'])

df['Date'] = pd.to_datetime(df['Date'], format='mixed')
df

           Date  duration
day1 2020-12-01        50
day2 2020-12-02        40
day3 2020-12-26        45

## 清洗错误数据

In [93]:
person = {
  "name": ['Google', 'Runoob' , 'Taobao'],
  "age": [50, 40, 12345]    # 12345 年龄数据是错误的
}

df = pd.DataFrame(person)

df.loc[2, 'age'] = 30
print(df.to_string())

# 条件语句清洗数据
person = {
  "name": ['Google', 'Runoob' , 'Taobao'],
  "age": [50, 200, 12345]    
}

df = pd.DataFrame(person)

for x in df.index:
    if df.loc[x, 'age'] > 120:
        df.loc[x, 'age'] = 120
df

     name  age
0  Google   50
1  Runoob   40
2  Taobao   30

     name  age
0  Google   50
1  Runoob  120
2  Taobao  120

## 数据分箱

In [ ]:
# pd.cut(data, bins, labels) bins:分箱的范围, labels: 分箱后范围的标签
df = pd.read_csv('data/employees.csv')
df1 = df[['employee_id', 'salary']].head(10)

df['收入级别'] = pd.cut(df['salary'], 
       bins=[0, 10000, 20000, 30000], 
       labels=['低', '中', '高'])
print(df['收入级别'].value_counts().to_string())

# pd.qcut() 等频分箱
print(pd.qcut(df1['salary'], q=3, labels=['低', '中', '高']).value_counts().to_string())

收入级别
低    92
中    14
高     1
salary
低    4
中    3
高    3

## 时间处理

In [111]:
import pandas as pd

d = pd.Timestamp('2026-08-17 22:10:03')

print(type(d))

print(d.year, d.month, d.day, d.hour, d.minute, d.second)
print('季度: ', d.quarter)
print('是否为月底: ', d.is_month_end)

# 方法
print('星期几: ', d.day_name())
print('转换为天: ', d.to_period('D'))
print('转换为月: ', d.to_period('M'))
print('转换为年: ', d.to_period('Y'))
print('转化为季度: ', d.to_period('Q'))
print('转换为周: ', d.to_period('W'))

<class 'pandas.Timestamp'>
2026 8 17 22 10 3
季度:  3
是否为月底:  False
星期几:  Monday
转换为天:  2026-08-17
转换为月:  2026-08
转换为年:  2026
转化为季度:  2026Q3
转换为周:  2026-08-17/2026-08-23

In [119]:
# 字符串转换为日期类型
a = pd.to_datetime('20260817221323')
print(a)
print(type(a))
print(a.day_name())

2026-08-17 22:13:23
<class 'pandas.Timestamp'>
Monday

In [134]:
# dataFrame 日期转换
df = pd.DataFrame({
    'sales': [100, 200, 300],
    'date': ['20260811', '20260812', '20260813']
})

df['datetime'] = pd.to_datetime(df['date'])

df['week'] = df['datetime'].dt.day_name()

df['datetime'].dt.year

0    2026
1    2026
2    2026
Name: datetime, dtype: int32

In [140]:
# CSV 日期转换
df = pd.read_csv('data/weather.csv', parse_dates=['date'])
df.info()
df['date'].dt.day_name()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 73.8 KB

0          Sunday
1          Monday
2         Tuesday
3       Wednesday
4        Thursday
          ...
1456       Sunday
1457       Monday
1458      Tuesday
1459    Wednesday
1460     Thursday
Name: date, Length: 1461, dtype: str

In [ ]:
# 创建时间序列
days = pd.date_range('2026-08-01', '2026-08-31', freq='W') # 按周生成时间序列
print(days)
days = pd.date_range('2026-08-01', periods=10, freq='W') # 按周创建10个时间序列
print(days)

DatetimeIndex(['2026-08-02', '2026-08-09', '2026-08-16', '2026-08-23',
               '2026-08-30'],
              dtype='datetime64[us]', freq='W-SUN')
DatetimeIndex(['2026-08-02', '2026-08-09', '2026-08-16', '2026-08-23',
               '2026-08-30', '2026-09-06', '2026-09-13', '2026-09-20',
               '2026-09-27', '2026-10-04'],
              dtype='datetime64[us]', freq='W-SUN')

In [157]:
# 重新采样
df = pd.read_csv('data/weather.csv', parse_dates=['date'])
df.set_index('date', inplace=True)
df[['temp_max', 'temp_min']].resample('YE').mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

## 分组聚合

In [ ]:
# df.groupby(分组字段)[聚合字段].聚合函数()

df = pd.read_csv('data/employees.csv')

# 删除缺失值
df = df.dropna(subset=['department_id'])

df.groupby('department_id').groups # 查看所有分组
df.groupby('department_id').get_group(10) # 查看某个分组的数据

df1 = df.groupby('department_id')[['salary']].mean().round(2)
df1 = df1.reset_index()
df1.sort_values('salary', ascending=False)

    department_id    salary
8            90.0  19333.33
10          110.0  10150.00
6            70.0  10000.00
1            20.0   9500.00
7            80.0   8955.88
9           100.0   8600.00
3            40.0   6500.00
5            60.0   5760.00
0            10.0   4400.00
2            30.0   4150.00
4            50.0   3475.56

In [187]:
# 两个字段聚合
df2 = df.groupby(['department_id', 'job_id'])[['salary']].mean()
df2 = df2.reset_index()
df2.sort_values('salary', ascending=False)

    department_id      job_id        salary
13           90.0     AD_PRES  24000.000000
14           90.0       AD_VP  17000.000000
1            20.0      MK_MAN  13000.000000
11           80.0      SA_MAN  12200.000000
16          100.0      FI_MGR  12000.000000
18          110.0      AC_MGR  12000.000000
4            30.0      PU_MAN  11000.000000
10           70.0      PR_REP  10000.000000
12           80.0      SA_REP   8396.551724
17          110.0  AC_ACCOUNT   8300.000000
15          100.0  FI_ACCOUNT   7920.000000
8            50.0      ST_MAN   7280.000000
5            40.0      HR_REP   6500.000000
2            20.0      MK_REP   6000.000000
9            60.0     IT_PROG   5760.000000
0            10.0     AD_ASST   4400.000000
6            50.0    SH_CLERK   3215.000000
7            50.0    ST_CLERK   2785.000000
3            30.0    PU_CLERK   2780.000000